name: Tests

on:
    push:
    pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        
      - name: Run test suite
        env:
          VINCARIO_API_KEY: ${{secrets.VINCARIO_API_KEY}}
          VINCARIO_API_SECRET: ${{secrets.VINCARIO_API_SECRET}}
          VINCARIO_VIN_NUMBER: ${{secrets.VINCARIO_VIN_NUMBER}}
          VINCARIO_VIN_NUMBER2: ${{secrets.VINCARIO_VIN_NUMBER2}}
          VINCARIO_VIN_NUMBER3: ${{secrets.VINCARIO_VIN_NUMBER3}}
        run: composer run-script testdox
